name=Adafruit_QSPIFs
version=1.0.0
author=Miocasa
maintainer=Miocasa <narimanabdualiev06@gmail.com>
sentence=Wrapper Library for Adafruit QSPI to work using Adafruit_LittleFs API
paragraph=Wrapper Library for Adafruit QSPI to work using Adafruit_LittleFs API
category=Data Storage
url=https://github.com/Miocasa/QSPIFileSystem
architectures=*
depends=Adafruit SPIFlash